# Название вашего воркфлоу. Отображается в GitHub Actions.
name: CI (Continuous Integration)

# Триггеры: когда запускать этот воркфлоу.
on:
  # Запускать при отправке (push) кода в ветку main.
  push:
    branches: [ main ]
  # Запускать при создании Pull Request в ветку main.
  pull_request:
    branches: [ main ]

# Задачи (Jobs), которые будут выполняться.
jobs:
  # Название задачи. Может быть любым (например, test-and-lint).
  build:
    # На какой операционной системе запускать. ubuntu-latest - стандартный бесплатный вариант.
    runs-on: ubuntu-latest

    # Стратегия для запуска на нескольких версиях Node.js (хорошая практика).
    strategy:
      matrix:
        node-version: [16.x, 18.x] # Вы можете указать нужные вам версии

    # Шаги (Steps), которые нужно выполнить в рамках задачи.
    steps:
      # Шаг 1: Скачивание вашего кода из репозитория на виртуальную машину.
      # 'uses' говорит о том, что мы используем готовое действие (action) от сообщества.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Настройка нужной версии Node.js.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      # Шаг 3: Установка зависимостей. 'npm ci' - более быстрая и надежная версия 'npm install' для CI.
      - name: Install dependencies
        run: npm ci

      # Шаг 4: Запуск линтера для проверки стиля кода.
      - name: Run linter
        run: npm run lint

      # Шаг 5: Запуск тестов. Jest будет автоматически запущен с покрытием.
      - name: Run tests
        run: npm test